// pages/report.js — REPORT VIEW (/reports/:id). Printable; every report shows
// audience, scope, range, generator and visibility.

import * as api from '../core/api.js';
import { can } from '../core/state.js';
import { setTitle } from '../core/layout.js';
import { esc, icon, fmt, errorBox, skeleton, empty, toast, $ } from '../core/ui.js';

export function reportBody(r) {
  const m = r.meta || {};
  const client = m.audience === 'client';
  const filters = Object.entries(m.filters || {});
  return `
    <div class="banner ${client ? 'info' : 'warning'}">${icon(client ? 'share' : 'lock')}<div class="grow"><b>${client ? 'CLIENT REPORT' : 'INTERNAL REPORT'}</b> — ${esc(m.visibility || '')}</div></div>
    <section class="card" style="margin-bottom:14px"><div class="card-b">
      <div class="row" style="align-items:flex-start"><div class="grow"><div class="muted" style="font-size:10.5px;letter-spacing:.14em;font-weight:800">CAMVIEW COMMAND CENTER · REPORT</div>
        <h2 style="margin:4px 0 0;font-size:20px">${esc(m.title || 'Report')}</h2></div>
        <span class="b ${client ? 'vis-shared' : 'vis-internal'}">${icon(client ? 'share' : 'lock')}${client ? 'Client audience' : 'Internal audience'}</span></div>
      <dl class="kv" style="margin-top:12px">
        <dt>Audience</dt><dd>${esc(m.audience)}${m.client ? ` · ${esc(m.client)}` : ''}</dd>
        <dt>Scope</dt><dd>${esc(m.scope || '—')}</dd>
        <dt>Data range</dt><dd>${esc(m.dataRange || '—')}</dd>
        <dt>Filters</dt><dd>${filters.length ? filters.map(([k, v]) => `<span class="b outline">${esc(k)}: ${esc(v)}</span>`).join(' ') : '<span class="muted">None</span>'}</dd>
        <dt>Records</dt><dd class="num">${fmt.n(m.recordCount)}</dd>
        <dt>Generated by</dt><dd>${esc(m.generatedBy || '—')}</dd>
        <dt>Generated at</dt><dd class="num">${fmt.dt(m.generatedAt)}</dd>
        <dt>Visibility</dt><dd>${esc(m.visibility || '—')}</dd>
      </dl></div></section>
    ${(r.sections || []).map((s) => `<section class="card" style="margin-bottom:14px"><div class="card-h"><h3>${esc(s.title)}</h3>${s.note ? `<div class="actions muted">${esc(s.note)}</div>` : ''}</div>
      <div class="card-b ${s.kind === 'table' ? 'flush' : ''}">${s.kind === 'kv'
        ? `<dl class="kv">${s.rows.map(([k, v]) => `<dt>${esc(k)}</dt><dd>${v == null ? '—' : esc(v)}</dd>`).join('')}</dl>`
        : s.rows.length ? `<div class="table-wrap" style="max-height:520px"><table class="t"><thead><tr>${s.columns.map((c) => `<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${s.rows.map((row) => `<tr>${row.map((v) => `<td>${v == null || v === '' ? '<span class="muted">—</span>' : esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`
          : empty('No rows')}</div></section>`).join('')}`;
}

export default {
  async render(el, ctx) {
    const id = ctx.params.id;
    setTitle('Report', `<a href="#/reports">Reports</a> / #${esc(id)}`);
    el.innerHTML = skeleton(8, 40);
    let r;
    const load = async () => {
      try { r = await api.get(`/api/reports/${encodeURIComponent(id)}`); if (!ctx.isStale()) paint(); }
      catch (e) {
        if (ctx.isStale()) return;
        el.innerHTML = e.status === 404 ? `<div class="error-state">${icon('report')}<div class="e-t">Report not available</div><a class="btn" href="#/reports">Back to reports</a></div>` : errorBox(e);
        $('[data-retry]', el)?.addEventListener('click', load);
      }
    };
    const paint = () => {
      const client = r.meta?.audience === 'client';
      setTitle(r.meta?.title || 'Report', `<a href="#/reports">Reports</a> / #${esc(id)}`);
      el.innerHTML = `
        <div class="page-head no-print"><div class="row" style="gap:12px"><a class="btn icon" href="#/reports" aria-label="Back to reports">${icon('left')}</a><div><h2>${esc(r.meta?.title || 'Report')}</h2><p>Report #${esc(id)}</p></div></div>
          <div class="row">
            ${client && can('report.share') ? `<button class="btn ${r.sharedWithClient ? '' : 'primary'}" id="rp-share">${icon('share', 's')} ${r.sharedWithClient ? 'Stop sharing' : 'Share with client'}</button>` : ''}
            ${client && r.sharedWithClient ? `<span class="b vis-shared">${icon('share')}shared with client</span>` : ''}
            ${can('report.export') ? `<button class="btn" id="rp-csv">${icon('download', 's')} CSV</button>` : ''}
            <button class="btn" id="rp-print">${icon('report', 's')} Print / PDF</button></div></div>
        ${reportBody(r)}`;
      $('#rp-print', el).addEventListener('click', () => window.print());
      $('#rp-csv', el)?.addEventListener('click', async () => {
        try { await api.download(`/api/reports/${encodeURIComponent(id)}/csv`); } catch (e) { toast(e.message, 'error'); }
      });
      $('#rp-share', el)?.addEventListener('click', async () => {
        try { await api.post(`/api/reports/${encodeURIComponent(id)}/share`, { share: !r.sharedWithClient }); toast(r.sharedWithClient ? 'No longer shared' : 'Shared with client', 'success'); load(); }
        catch (e) { toast(e.message, 'error'); }
      });
    };
    await load();
  },
};
